### ISSUE TITLE
[Question] Are there any mechanisms to pass a result of Promise into WASM(Rust) code? And how do you use it?

### ISSUE THREAD

**Issue by y-ich** [koute/stdweb#138]
Hi.

I want to pass a result of JS Promise into Rust code like the below.

```rust
let result = js! { await asyncFunc(@{some_value}) };
```

I tried such a code but got an error "SyntaxError: Unexpected identifier 'asyncFunc'" when loading generated js file.

I should use rather Promise but I have no idea how I can take the result out from js! macro.

**Comment by kngwyu** [comment]
stdweb has ```PromiseFuture```.
In your Cargo.toml
```toml
[dependencies]
futures = "0.1"
[dependencies.stdweb]
version = "0.4"
features = ["experimental_features_which_may_break_on_minor_version_bumps"]
```
and 
``` rust
use stdweb::{Promise, PromiseFuture};
use futures::Future;
let promise = Promise::from_thenable(&js! {
    return new Promise(function (resolve, reject) {
        // some code
    })}.try_into()
        .unwrap());
let future = promise.unwrap().to_future().
```
will work, though it's experimental (see #127).
